// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBThYtBLCS1qVjt3nOClJd5oJ4iXhkHw',
    appId: '1:889500629302:web:361381f9a04e13da145b97',
    messagingSenderId: '889500629302',
    projectId: 'ica12-e3ff8',
    authDomain: 'ica12-e3ff8.firebaseapp.com',
    storageBucket: 'ica12-e3ff8.firebasestorage.app',
    measurementId: 'G-G70VWTJLKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSmLoCIUaPpCQZlalpRBfw7BEw6F_zZ50',
    appId: '1:889500629302:android:3d57136e59e4404b145b97',
    messagingSenderId: '889500629302',
    projectId: 'ica12-e3ff8',
    storageBucket: 'ica12-e3ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAScFvJ7a8kWByQK1E7nBWWkn3dz-CgjxE',
    appId: '1:889500629302:ios:910682389e138afd145b97',
    messagingSenderId: '889500629302',
    projectId: 'ica12-e3ff8',
    storageBucket: 'ica12-e3ff8.firebasestorage.app',
    iosBundleId: 'com.example.ica12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAScFvJ7a8kWByQK1E7nBWWkn3dz-CgjxE',
    appId: '1:889500629302:ios:910682389e138afd145b97',
    messagingSenderId: '889500629302',
    projectId: 'ica12-e3ff8',
    storageBucket: 'ica12-e3ff8.firebasestorage.app',
    iosBundleId: 'com.example.ica12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGBThYtBLCS1qVjt3nOClJd5oJ4iXhkHw',
    appId: '1:889500629302:web:c2538ad6df01be21145b97',
    messagingSenderId: '889500629302',
    projectId: 'ica12-e3ff8',
    authDomain: 'ica12-e3ff8.firebaseapp.com',
    storageBucket: 'ica12-e3ff8.firebasestorage.app',
    measurementId: 'G-EDQ8GTNRJG',
  );

}